apiVersion: v1
kind: Service
metadata:
  name: studysync-frontend
  labels:
    name: studysync-frontend
spec:
  ports:
    - nodePort: 30162
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: studysync-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studysync-frontend
spec:
  selector:
    matchLabels:
      app: studysync-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: studysync-frontend
    spec:
      containers:
        - name: studysync-frontend
          image: jahidem/studysync-client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_HOSTNAME_DB
              valueFrom:
                configMapKeyRef:
                  key: hostname_db
                  name: studysync-configmap
            - name: NEXT_PUBLIC_HOSTNAME_SERVER
              valueFrom:
                configMapKeyRef:
                  key: hostname_server
                  name: studysync-configmap
            - name: NEXT_PUBLIC_HOSTNAME_AI
              valueFrom:
                configMapKeyRef:
                  key: hostname_ai
                  name: studysync-configmap
